export const INIT_STUDENT = 'INIT_STUDENT'
export const IMPORT_STUDENT = 'IMPORT_STUDENT'
export const DESTROY_STUDENT = 'DESTROY_STUDENT'

export const CHANGE_NAME = 'CHANGE_NAME'
export const CHANGE_ADVISOR = 'CHANGE_ADVISOR'
export const CHANGE_CREDITS_NEEDED = 'CHANGE_CREDITS_NEEDED'
export const CHANGE_MATRICULATION = 'CHANGE_MATRICULATION'
export const CHANGE_GRADUATION = 'CHANGE_GRADUATION'
export const CHANGE_SETTING = 'CHANGE_SETTING'

export const ADD_AREA = 'ADD_AREA'
export const REMOVE_AREA = 'REMOVE_AREA'
export const REMOVE_MULTIPLE_AREAS = 'REMOVE_MULTIPLE_AREAS'

export const ADD_SCHEDULE = 'ADD_SCHEDULE'
export const DESTROY_SCHEDULE = 'DESTROY_SCHEDULE'
export const DESTROY_MULTIPLE_SCHEDULES = 'DESTROY_MULTIPLE_SCHEDULES'
export const RENAME_SCHEDULE = 'RENAME_SCHEDULE'
export const REORDER_SCHEDULE = 'REORDER_SCHEDULE'
export const MOVE_SCHEDULE = 'MOVE_SCHEDULE'

export const ADD_COURSE = 'ADD_COURSE'
export const REMOVE_COURSE = 'REMOVE_COURSE'
export const REORDER_COURSE = 'REORDER_COURSE'
export const MOVE_COURSE = 'MOVE_COURSE'

export const SET_OVERRIDE = 'SET_OVERRIDE'
export const REMOVE_OVERRIDE = 'REMOVE_OVERRIDE'

export const ADD_FABRICATION = 'ADD_FABRICATION'
export const REMOVE_FABRICATION = 'REMOVE_FABRICATION'
