clone_folder: c:\projects\gobbldygook

# From http://stackoverflow.com/a/31882307/2347774
# Hopefully prevent appveyor from building twice for PRs
branches:
  only:
    - master

# the basic outline for this install process is from
# github.com/googlesamples/android-ndk/blob/master/appveyor.yml
install:
  # install node and npm packages
  - ps: Install-Product node $env:nodejs_version
  - yarn

environment:
  nodejs_version: '6'

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - yarn --version
  # run tests
  - yarn run lint
  - yarn test

build_script:
  - yarn run build-ci
