// flow-typed signature: 6d1baffe934b5d7c2830baf23b0ac7aa
// flow-typed version: <<STUB>>/appdirs_v1.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'appdirs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'appdirs' {
  declare module.exports: any;
}
