// flow-typed signature: 92324df15cd6079be04af095ae354758
// flow-typed version: <<STUB>>/appdirs_v^1.1.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'appdirs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'appdirs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'appdirs/index' {
  declare module.exports: $Exports<'appdirs'>;
}
declare module 'appdirs/index.js' {
  declare module.exports: $Exports<'appdirs'>;
}
