// flow-typed signature: 7cda6d77919a8ad9d96f2f9020f61d4c
// flow-typed version: <<STUB>>/babel-stdin_v1.0.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-stdin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-stdin' {
  declare module.exports: any;
}
