// flow-typed signature: 3d76753e15936d8b688b1c3f4dda575a
// flow-typed version: <<STUB>>/babel-plugin-transform-inline-environment-variables_v^6.8.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-inline-environment-variables'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-inline-environment-variables' {
  declare module.exports: any;
}
