// flow-typed signature: d8b6d6201e8424ea3adf1ea13670585b
// flow-typed version: <<STUB>>/babel-loader_v7.1.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-loader' {
  declare module.exports: any;
}
