// flow-typed signature: 0077825129674a7191931d598de03895
// flow-typed version: <<STUB>>/babel-core_v6.24.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-core' {
  declare module.exports: any;
}
