// flow-typed signature: 063649c4b248a39a343aac182c3c066f
// flow-typed version: <<STUB>>/babel-preset-latest_v6.22.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-latest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-latest' {
  declare module.exports: any;
}
