// flow-typed signature: 821da3e30fd7bb903721399e7abbcacd
// flow-typed version: <<STUB>>/babel-plugin-external-helpers_v6.22.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-external-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-external-helpers' {
  declare module.exports: any;
}
