// flow-typed signature: 6042e34dadbecf04525d9420dad4b77b
// flow-typed version: <<STUB>>/babel-register_v6.22.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-register'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-register' {
  declare module.exports: any;
}
