// flow-typed signature: eb74959177edb732c744e00f2d0df43a
// flow-typed version: <<STUB>>/babel-jest_v22.4.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-jest' {
  declare module.exports: any;
}
