// flow-typed signature: 1e16722b398adbbe2c7477ed27228851
// flow-typed version: <<STUB>>/babel-register_v6.24.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-register'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-register' {
  declare module.exports: any;
}
