// flow-typed signature: 30f2e8812dc842f271b798ebc7d0af39
// flow-typed version: <<STUB>>/babel-runtime_v6.23.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-runtime' {
  declare module.exports: any;
}
