// flow-typed signature: 4856f740e3dd67388b12e643b7a0153a
// flow-typed version: <<STUB>>/babel-plugin-styled-components_v^1.5.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-styled-components' {
  declare module.exports: any;
}
