// flow-typed signature: bda3a77185ea3a353196e1409d969036
// flow-typed version: <<STUB>>/babel-preset-env_v^1.6.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-env' {
  declare module.exports: any;
}
