// flow-typed signature: c30230f248b361bdacab0a225fb7f53e
// flow-typed version: <<STUB>>/babel-preset-env_v1.2.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-env' {
  declare module.exports: any;
}
