// flow-typed signature: 23a8e15b9066e7aabfcf6227ea413c9f
// flow-typed version: <<STUB>>/babel-plugin-transform-runtime_v6.23.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-runtime' {
  declare module.exports: any;
}
