// flow-typed signature: a9340b9df76b7674f31e109557df2323
// flow-typed version: <<STUB>>/babel-stdin_v^1.1.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-stdin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-stdin' {
  declare module.exports: any;
}
