// flow-typed signature: 5153e3dc162c941b6e1ad8a39180c083
// flow-typed version: <<STUB>>/babel-plugin-transform-runtime_v^6.23.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-runtime' {
  declare module.exports: any;
}
