// flow-typed signature: 5c7f58d906d691b46a1328597430c277
// flow-typed version: <<STUB>>/babel-eslint_v7.2.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-eslint' {
  declare module.exports: any;
}
