// flow-typed signature: 3fc3832701d585a15e2ae828ca963f30
// flow-typed version: <<STUB>>/babel-plugin-transform-class-properties_v6.23.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-class-properties'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-class-properties' {
  declare module.exports: any;
}
