// flow-typed signature: 3aba6af54d306eb558b654fed0a008ce
// flow-typed version: <<STUB>>/babel-runtime_v6.26.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-runtime' {
  declare module.exports: any;
}
