// flow-typed signature: b106292d29d4a19ba206b70893e13e57
// flow-typed version: <<STUB>>/babel-plugin-transform-react-constant-elements_v6.23.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-react-constant-elements'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-react-constant-elements' {
  declare module.exports: any;
}
