// flow-typed signature: 01c50bcb93f43275311bf9a03aac898a
// flow-typed version: <<STUB>>/babel-eslint_v^8.2.6/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-eslint' {
  declare module.exports: any;
}
