// flow-typed signature: ce3658d957be501766e50d73c72f6cea
// flow-typed version: <<STUB>>/babel-preset-react_v6.24.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-react' {
  declare module.exports: any;
}
