// flow-typed signature: a50c3be4cfffa87a3ad43e697c9130be
// flow-typed version: <<STUB>>/babel-preset-react_v6.23.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-react' {
  declare module.exports: any;
}
