// flow-typed signature: 2fad067ccc9f4f0df1e08947e0dc25df
// flow-typed version: <<STUB>>/babel-plugin-lodash_v3.2.11/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-lodash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-lodash' {
  declare module.exports: any;
}
