// flow-typed signature: eea08eb2e1b5f36c334968e08cdc2c90
// flow-typed version: <<STUB>>/babel-plugin-webpack-alias_v1.9.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-webpack-alias'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-webpack-alias' {
  declare module.exports: any;
}
