// flow-typed signature: 3fce22d90648a2357d0a609c67408348
// flow-typed version: <<STUB>>/babel-preset-react_v6.22.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-react' {
  declare module.exports: any;
}
