// flow-typed signature: 479f96f7f545e87ab86c11e8927013a9
// flow-typed version: <<STUB>>/babel-eslint_v7.1.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-eslint' {
  declare module.exports: any;
}
