// flow-typed signature: 652227dd28d39cb60ed617d1132b0822
// flow-typed version: <<STUB>>/babel-plugin-transform-es2015-modules-commonjs_v^6.26.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-es2015-modules-commonjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-es2015-modules-commonjs' {
  declare module.exports: any;
}
