// flow-typed signature: be6dcadb3279f49bb76ba82f0bbe1c18
// flow-typed version: <<STUB>>/babel-preset-flow_v^6.23.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-flow' {
  declare module.exports: any;
}
