// flow-typed signature: 9d78923ba212b12e6b0838ce2484d630
// flow-typed version: <<STUB>>/babel-plugin-lodash_v3.3.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-lodash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-lodash' {
  declare module.exports: any;
}
