// flow-typed signature: 493290418fe216e7bb4aa0c55e1b5215
// flow-typed version: <<STUB>>/babel-loader_v7.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-loader' {
  declare module.exports: any;
}
