// flow-typed signature: fe33ea2756efc243a0f67c225a1e225c
// flow-typed version: <<STUB>>/babel-plugin-transform-runtime_v6.23.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-runtime' {
  declare module.exports: any;
}
