// flow-typed signature: 254ca73cf0da744e125ea4ca4b414537
// flow-typed version: <<STUB>>/babel-plugin-transform-object-rest-spread_v6.26.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-object-rest-spread'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-object-rest-spread' {
  declare module.exports: any;
}
