// flow-typed signature: d80a7b586bbec974855825e2b0f4b8f6
// flow-typed version: <<STUB>>/babel-plugin-istanbul_v3.1.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-istanbul'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-istanbul' {
  declare module.exports: any;
}
