// flow-typed signature: 5bee0615fe6f493380b771499c74e9a2
// flow-typed version: <<STUB>>/babel-plugin-transform-react-display-name_v^6.25.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-react-display-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-react-display-name' {
  declare module.exports: any;
}
