// flow-typed signature: 9470f30a308e13969d3371d932e09859
// flow-typed version: <<STUB>>/babel-plugin-transform-react-inline-elements_v^6.22.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-react-inline-elements'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-react-inline-elements' {
  declare module.exports: any;
}
