// flow-typed signature: 7053f1de4803dac5e3d8efa5d526b48b
// flow-typed version: <<STUB>>/babel-plugin-transform-inline-environment-variables_v6.8.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-inline-environment-variables'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-inline-environment-variables' {
  declare module.exports: any;
}
