// flow-typed signature: ffe836458a2de40be08a762365e8e5ee
// flow-typed version: <<STUB>>/babel-runtime_v6.22.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-runtime' {
  declare module.exports: any;
}
