// flow-typed signature: f30830d3ebb866c83b134743d60befe6
// flow-typed version: <<STUB>>/babel-loader_v7.1.4/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-loader' {
  declare module.exports: any;
}
