// flow-typed signature: 890976d43ed7dbf06f6472d91ee50914
// flow-typed version: <<STUB>>/babel-plugin-transform-react-constant-elements_v^6.23.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-react-constant-elements'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-react-constant-elements' {
  declare module.exports: any;
}
