// flow-typed signature: f47a3133eab7af365bfab1e547c3a313
// flow-typed version: <<STUB>>/babel-stdin_v^1.1.1/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-stdin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-stdin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-stdin/babel-stdin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-stdin/babel-stdin.js' {
  declare module.exports: $Exports<'babel-stdin/babel-stdin'>;
}
