// flow-typed signature: 0d573570a117ceebe70ea2d1983b7c05
// flow-typed version: <<STUB>>/babel-register_v^6.26.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-register'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-register' {
  declare module.exports: any;
}
