// flow-typed signature: 15c0dc22e78addd6eed45c6139d9ebc7
// flow-typed version: <<STUB>>/babel-plugin-lodash_v^3.3.4/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-lodash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-lodash' {
  declare module.exports: any;
}
