// flow-typed signature: 98efb250bc1076a6afb65f300c25a047
// flow-typed version: <<STUB>>/babel-plugin-transform-inline-environment-variables_v6.8.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-inline-environment-variables'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-inline-environment-variables' {
  declare module.exports: any;
}
