// flow-typed signature: 640dcf7cdffdff8dddcaaf78dadb5f3c
// flow-typed version: <<STUB>>/babel-core_v^6.26.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-core' {
  declare module.exports: any;
}
