// flow-typed signature: 2415eb0d0357f7b7f87679637ea8ca4c
// flow-typed version: <<STUB>>/babel-plugin-transform-class-properties_v6.24.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-class-properties'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-class-properties' {
  declare module.exports: any;
}
