// flow-typed signature: e3ca7ce5dbf00d0da563f8d8dff29af7
// flow-typed version: <<STUB>>/babel-core_v^6.26.3/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-core' {
  declare module.exports: any;
}
