// flow-typed signature: f2370d46b6c9d8319dd19664361bbd93
// flow-typed version: <<STUB>>/babel-plugin-transform-es2015-modules-commonjs_v6.26.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-es2015-modules-commonjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-es2015-modules-commonjs' {
  declare module.exports: any;
}
