// flow-typed signature: 4a4e341ed0e454bf2c7bee2cca92cbba
// flow-typed version: <<STUB>>/babel-plugin-transform-react-constant-elements_v6.22.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-react-constant-elements'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-react-constant-elements' {
  declare module.exports: any;
}
