// flow-typed signature: d7f6e5d4e663f8abbea5a70953e19d04
// flow-typed version: <<STUB>>/babel-plugin-transform-object-rest-spread_v^6.26.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-object-rest-spread'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-object-rest-spread' {
  declare module.exports: any;
}
