// flow-typed signature: 12767af4a3b2b78655c904986bcac049
// flow-typed version: <<STUB>>/babel-plugin-transform-react-display-name_v6.25.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-react-display-name'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-react-display-name' {
  declare module.exports: any;
}
