// flow-typed signature: 8532852bdf2e624ae3cc9301d1da18c3
// flow-typed version: <<STUB>>/brwsr_v1.0.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'brwsr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'brwsr' {
  declare module.exports: any;
}
