// flow-typed signature: c620576fe314bfc82c7d56cf6bc514db
// flow-typed version: <<STUB>>/bugsnag-js_v^4.7.3/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bugsnag-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bugsnag-js' {
  declare module.exports: any;
}
