// flow-typed signature: b32dc95e93c2701ebb367dd79cadc3a9
// flow-typed version: <<STUB>>/case-sensitive-paths-webpack-plugin_v1.1.4/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'case-sensitive-paths-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'case-sensitive-paths-webpack-plugin' {
  declare module.exports: any;
}
