// flow-typed signature: 6286b8e8c56508e81bb5a2df71e13b8c
// flow-typed version: <<STUB>>/case-sensitive-paths-webpack-plugin_v^2.1.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'case-sensitive-paths-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'case-sensitive-paths-webpack-plugin' {
  declare module.exports: any;
}
