// flow-typed signature: 7b8a00986142f394b06210bf9ed08f23
// flow-typed version: <<STUB>>/case-sensitive-paths-webpack-plugin_v2.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'case-sensitive-paths-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'case-sensitive-paths-webpack-plugin' {
  declare module.exports: any;
}
