// flow-typed signature: 472a4d0db7e07ec58cb6002bf307d1d4
// flow-typed version: <<STUB>>/chai_v4.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chai' {
  declare module.exports: any;
}
