// flow-typed signature: b8e5525749b620c3676d9e610e1dbcd9
// flow-typed version: <<STUB>>/clean-webpack-plugin_v0.1.19/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clean-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clean-webpack-plugin' {
  declare module.exports: any;
}
