// flow-typed signature: e1cb673be72ed796a3779228a75ba2d3
// flow-typed version: <<STUB>>/codemirror_v^5.40.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'codemirror'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'codemirror' {
  declare module.exports: any;
}
