// flow-typed signature: 0c86c1610b60693f19707bc78b857216
// flow-typed version: <<STUB>>/codemirror_v5.34.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'codemirror'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'codemirror' {
  declare module.exports: any;
}
