// flow-typed signature: 76537a9a3b3fd6b77adc0c455c9c282e
// flow-typed version: <<STUB>>/codemirror_v5.26.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'codemirror'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'codemirror' {
  declare module.exports: any;
}
