// flow-typed signature: ec28f332b333281781b5f860c1af491a
// flow-typed version: <<STUB>>/copy-webpack-plugin_v^4.5.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'copy-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'copy-webpack-plugin' {
  declare module.exports: any;
}
