// flow-typed signature: 590ca3b0f9237e3d73b6a694f262c60f
// flow-typed version: <<STUB>>/copy-webpack-plugin_v4.3.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'copy-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'copy-webpack-plugin' {
  declare module.exports: any;
}
