// flow-typed signature: 584872d3e7fff3dc3c6ae815a1c7e78e
// flow-typed version: <<STUB>>/coveralls_v^3.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'coveralls'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'coveralls' {
  declare module.exports: any;
}
