// flow-typed signature: 25cba37d3258c7b3ca69ff90125a85bf
// flow-typed version: <<STUB>>/coveralls_v^3.0.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'coveralls'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'coveralls' {
  declare module.exports: any;
}
