// flow-typed signature: 1f5c1c81a197e9a80cf63c0854a70335
// flow-typed version: <<STUB>>/coveralls_v3.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'coveralls'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'coveralls' {
  declare module.exports: any;
}
