// flow-typed signature: 9dcd7308add8cdc102e67c425bd02247
// flow-typed version: <<STUB>>/cpy-cli_v1.0.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cpy-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cpy-cli' {
  declare module.exports: any;
}
