// flow-typed signature: 9a7ea9b34f7087abcc9a38c299ac6b1f
// flow-typed version: <<STUB>>/cpy-cli_v1.0.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cpy-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cpy-cli' {
  declare module.exports: any;
}
