// flow-typed signature: 4736be9e730accfc8152c48bd1fa4c8c
// flow-typed version: <<STUB>>/cpy_v^6.0.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cpy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cpy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cpy/cpy-error' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cpy/cpy-error.js' {
  declare module.exports: $Exports<'cpy/cpy-error'>;
}
declare module 'cpy/index' {
  declare module.exports: $Exports<'cpy'>;
}
declare module 'cpy/index.js' {
  declare module.exports: $Exports<'cpy'>;
}
