// flow-typed signature: aa37154cf3c8caf41370b829db4c7f9a
// flow-typed version: <<STUB>>/cross-env_v3.1.4/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cross-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cross-env' {
  declare module.exports: any;
}
