// flow-typed signature: c2d49a966e910b62b6510685c34927d2
// flow-typed version: <<STUB>>/cross-env_v^5.2.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cross-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cross-env' {
  declare module.exports: any;
}
