// flow-typed signature: 52f68e3874a2d38b961a422f4801717b
// flow-typed version: <<STUB>>/css-loader_v^1.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-loader' {
  declare module.exports: any;
}
