// flow-typed signature: c772c62636414bf30cbb422675bb9c2c
// flow-typed version: <<STUB>>/css-loader_v0.28.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-loader' {
  declare module.exports: any;
}
