// flow-typed signature: 9b3b5e9e99c5de9a33ace0083abd3ee2
// flow-typed version: <<STUB>>/css-loader_v0.26.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-loader' {
  declare module.exports: any;
}
