// flow-typed signature: 96a7d7512b39d8aaf58b6e5184792437
// flow-typed version: <<STUB>>/css-select_v1.2.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-select' {
  declare module.exports: any;
}
