// flow-typed signature: d5614df0b89636430f826a09b6437665
// flow-typed version: <<STUB>>/debug_v^4.0.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'debug'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'debug' {
  declare module.exports: any;
}
