// flow-typed signature: 7a1289a79a34c71693c86552ad660e7f
// flow-typed version: <<STUB>>/dedent_v0.7.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dedent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dedent' {
  declare module.exports: any;
}
