// flow-typed signature: 49dc04b3d2a81c12c0b38bff9cc91cc2
// flow-typed version: <<STUB>>/dedent_v0.7.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dedent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dedent' {
  declare module.exports: any;
}
