// flow-typed signature: 516455ab8a8b8dc78f18e78cf345d05b
// flow-typed version: <<STUB>>/del_v^3.0.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'del'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'del' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'del/index' {
  declare module.exports: $Exports<'del'>;
}
declare module 'del/index.js' {
  declare module.exports: $Exports<'del'>;
}
