// flow-typed signature: 771cd2f46a841702570d47472e9a5998
// flow-typed version: <<STUB>>/delay_v2.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'delay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'delay' {
  declare module.exports: any;
}
