// flow-typed signature: 6da67ad29ecbbb509fa58dd3c32748ea
// flow-typed version: <<STUB>>/delay_v1.3.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'delay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'delay' {
  declare module.exports: any;
}
