// flow-typed signature: fbc4edabc4ce688e3b987ca641fdded3
// flow-typed version: <<STUB>>/duplicate-package-checker-webpack-plugin_v1.2.4/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'duplicate-package-checker-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'duplicate-package-checker-webpack-plugin' {
  declare module.exports: any;
}
