// flow-typed signature: 7bd03e3d60caea193cd30d109ec90ac7
// flow-typed version: <<STUB>>/duplicate-package-checker-webpack-plugin_v^3.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'duplicate-package-checker-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'duplicate-package-checker-webpack-plugin' {
  declare module.exports: any;
}
