// flow-typed signature: 4d590072b60dfef114c6a6d0f2d4e6b7
// flow-typed version: <<STUB>>/duplicate-package-checker-webpack-plugin_v2.1.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'duplicate-package-checker-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'duplicate-package-checker-webpack-plugin' {
  declare module.exports: any;
}
