// flow-typed signature: 3d85e046fc4accba97eb98a8136d846c
// flow-typed version: <<STUB>>/enzyme-adapter-react-16_v1.1.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enzyme-adapter-react-16'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enzyme-adapter-react-16' {
  declare module.exports: any;
}
