// flow-typed signature: 702575f6feddc35c9beec2fa07dcf9b5
// flow-typed version: <<STUB>>/enzyme-to-json_v1.5.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enzyme-to-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enzyme-to-json' {
  declare module.exports: any;
}
