// flow-typed signature: 8d43d6da060c9cefc135d41d8dd55627
// flow-typed version: <<STUB>>/enzyme-adapter-react-16_v^1.5.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'enzyme-adapter-react-16'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'enzyme-adapter-react-16' {
  declare module.exports: any;
}
