// flow-typed signature: cf4ca595b38b57bd221ba4e64db7c451
// flow-typed version: <<STUB>>/es6-set_v0.1.4/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es6-set'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es6-set' {
  declare function exports<T>(): Set<T>;
}
