// flow-typed signature: e507e40cda46a48bffdf78b28d0803c3
// flow-typed version: <<STUB>>/es6-promise_v4.2.4/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es6-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es6-promise' {
  declare module.exports: any;
}
