// flow-typed signature: a21ed1f1c0921b29910c1116db17088e
// flow-typed version: <<STUB>>/es6-set_v0.1.5/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es6-set'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es6-set' {
  declare module.exports: any;
}
