// flow-typed signature: 01f89894f8127a07943ca8a37b4200d2
// flow-typed version: <<STUB>>/es6-promise_v4.1.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es6-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es6-promise' {
  declare module.exports: any;
}
