// flow-typed signature: f0d851e6a2caad365ead94513d37e0b2
// flow-typed version: <<STUB>>/es6-set_v0.1.4/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es6-set'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es6-set' {
  declare function exports<T>(): Set<T>;
}
