// flow-typed signature: 369203f4c9e6fc6861597891c434d1a0
// flow-typed version: <<STUB>>/es6-promise_v^4.2.5/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es6-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es6-promise' {
  declare module.exports: any;
}
