// flow-typed signature: 20b35ccb63173b7885dd6f63b08e305a
// flow-typed version: <<STUB>>/eslint-config-prettier_v2.1.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-prettier' {
  declare module.exports: any;
}
