// flow-typed signature: 11302f8b5823ff5b2e1767d5508f4c88
// flow-typed version: <<STUB>>/eslint_v^5.1.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint' {
  declare module.exports: any;
}
