// flow-typed signature: 688253e12830d3415cb2400c1e9523c4
// flow-typed version: <<STUB>>/eslint-plugin-babel_v4.1.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-babel' {
  declare module.exports: any;
}
