// flow-typed signature: 15f83cdea44a87e6231f3668ab4cbc4d
// flow-typed version: <<STUB>>/eslint-plugin-import_v2.8.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-import' {
  declare module.exports: any;
}
