// flow-typed signature: 5cea4bdb34a7dc437a20eb83d35cb4fd
// flow-typed version: <<STUB>>/eslint-plugin-react_v^7.10.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react' {
  declare module.exports: any;
}
