// flow-typed signature: 7e331b8b0d36d02605f92e7ec19b7885
// flow-typed version: <<STUB>>/eslint-plugin-flowtype-errors_v3.3.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-flowtype-errors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-flowtype-errors' {
  declare module.exports: any;
}
