// flow-typed signature: af5a9e34d1083eb2762a89e07803520b
// flow-typed version: <<STUB>>/eslint-plugin-react_v7.6.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react' {
  declare module.exports: any;
}
