// flow-typed signature: b6cee62d06ad86db0962aa2f6179c48f
// flow-typed version: <<STUB>>/eslint-plugin-flowtype_v^2.46.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-flowtype'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-flowtype' {
  declare module.exports: any;
}
