// flow-typed signature: bda85f67de592b618be46c15c00f719a
// flow-typed version: <<STUB>>/eslint-plugin-babel_v4.0.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-babel' {
  declare module.exports: any;
}
