// flow-typed signature: 22a63ce9ed22d4808d5e55798d1ac0f6
// flow-typed version: <<STUB>>/eslint-plugin-flowtype_v^2.50.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-flowtype'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-flowtype' {
  declare module.exports: any;
}
