// flow-typed signature: 59f5b2c0140e73e67528e5185f0309a7
// flow-typed version: <<STUB>>/eslint-config-prettier_v^3.0.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-prettier' {
  declare module.exports: any;
}
