// flow-typed signature: 90c76b00aaa692b0ddd3e7b99f5e8a8d
// flow-typed version: <<STUB>>/eslint-plugin-babel_v5.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-babel' {
  declare module.exports: any;
}
