// flow-typed signature: 23d7c334a2b3ee665c6b0f61ba37709c
// flow-typed version: <<STUB>>/eslint-plugin-flowtype-errors_v2.0.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-flowtype-errors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-flowtype-errors' {
  declare module.exports: any;
}
