// flow-typed signature: a3586b98d4a6733becfae143adabfd88
// flow-typed version: <<STUB>>/eslint-plugin-flowtype-errors_v3.0.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-flowtype-errors'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-flowtype-errors' {
  declare module.exports: any;
}
