// flow-typed signature: 5664bb9ec17482762c6d6b32b17a94df
// flow-typed version: <<STUB>>/eslint_v4.19.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint' {
  declare module.exports: any;
}
