// flow-typed signature: 678caaa4fa4b5b33412eaacde9704b2e
// flow-typed version: <<STUB>>/eslint-plugin-react_v^7.7.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react' {
  declare module.exports: any;
}
