// flow-typed signature: e65e4941b570ae086e629cc34cc78109
// flow-typed version: <<STUB>>/eslint_v3.19.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint' {
  declare module.exports: any;
}
