// flow-typed signature: 44a0b65dda35e54aadac1f304c748b94
// flow-typed version: <<STUB>>/esm_v^3.0.84/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esm' {
  declare module.exports: any;
}
