// flow-typed signature: 20d494c8a21977b789a6bd2e5e5e6841
// flow-typed version: <<STUB>>/extract-text-webpack-plugin_v2.1.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extract-text-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'extract-text-webpack-plugin' {
  declare module.exports: any;
}
