// flow-typed signature: fc8f11910af2645a4c21ec57232dd5fd
// flow-typed version: <<STUB>>/extract-text-webpack-plugin_v3.0.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extract-text-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'extract-text-webpack-plugin' {
  declare module.exports: any;
}
