// flow-typed signature: df95b1967bff88a29dff94c59667756e
// flow-typed version: <<STUB>>/extract-text-webpack-plugin_v2.0.0-beta.5/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extract-text-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'extract-text-webpack-plugin' {
  declare module.exports: any;
}
