// flow-typed signature: fe8348ef1a63e6eeabba4867d2970d42
// flow-typed version: <<STUB>>/fake-indexeddb_v^2.0.4/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fake-indexeddb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fake-indexeddb' {
  declare module.exports: any;
}
