// flow-typed signature: bec1eac180b2c165decff2171e327e53
// flow-typed version: <<STUB>>/fake-indexeddb_v2.0.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fake-indexeddb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fake-indexeddb' {
  declare module.exports: any;
}
