// flow-typed signature: 6c7bb610130311900b3bea384bdd857b
// flow-typed version: <<STUB>>/fake-indexeddb_v2.0.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fake-indexeddb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fake-indexeddb' {
  declare module.exports: any;
}
