// flow-typed signature: ae11c2581ec386b2e04badc1c2b453ff
// flow-typed version: <<STUB>>/file-loader_v1.1.6/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'file-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'file-loader' {
  declare module.exports: any;
}
