// flow-typed signature: 1c8d789ae508854fcfadd18b2ac21742
// flow-typed version: <<STUB>>/file-loader_v^2.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'file-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'file-loader' {
  declare module.exports: any;
}
