// flow-typed signature: 5c6fc99542d83426af1ff74a4a5616a1
// flow-typed version: <<STUB>>/file-loader_v0.11.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'file-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'file-loader' {
  declare module.exports: any;
}
