// flow-typed signature: 4667f930f95a030ece4bedbae75792a8
// flow-typed version: <<STUB>>/flow-remove-types_v1.2.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-remove-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-remove-types' {
  declare module.exports: any;
}
