// flow-typed signature: 139b36adf501d0933aaf22d71192d4ea
// flow-typed version: <<STUB>>/flow-coverage-report_v^0.6.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-coverage-report'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-coverage-report' {
  declare module.exports: any;
}
