// flow-typed signature: 844629d5359f506da579a00912d1a6f1
// flow-typed version: <<STUB>>/flow-remove-types_v1.2.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-remove-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-remove-types' {
  declare module.exports: any;
}
