// flow-typed signature: 3e68b36f6373d24741a75af053ccad5c
// flow-typed version: <<STUB>>/fuzzysearch_v1.0.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fuzzysearch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fuzzysearch' {
  declare module.exports: any;
}
