// flow-typed signature: d4251312a898fc03333e5343de3f247b
// flow-typed version: <<STUB>>/fuzzysearch_v1.0.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fuzzysearch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fuzzysearch' {
  declare module.exports: any;
}
