// flow-typed signature: fb463b1d601bbb0d928bf4437c27e7f4
// flow-typed version: <<STUB>>/get-stdin_v^6.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'get-stdin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'get-stdin' {
  declare module.exports: any;
}
