// flow-typed signature: 76d65dfc169450ca3031d970aa67fa1e
// flow-typed version: <<STUB>>/glob_v7.1.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glob'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glob' {
  declare module.exports: any;
}
