// flow-typed signature: 54d2507ce60ae6df32b73db0069fe45a
// flow-typed version: <<STUB>>/glob_v^7.1.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glob'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glob' {
  declare module.exports: any;
}
