// flow-typed signature: 1e789b3fcbca7d2bc57aa17e153efd46
// flow-typed version: <<STUB>>/got_v^9.2.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'got'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'got' {
  declare module.exports: any;
}
