// flow-typed signature: 52d357bcb5d5535c09696b235f143c2c
// flow-typed version: <<STUB>>/history_v3.3.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'history'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'history' {
  declare module.exports: any;
}
