// flow-typed signature: d18e8e1204f71ee7207901a2978c3088
// flow-typed version: <<STUB>>/htmlparser2_v3.9.2/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'htmlparser2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'htmlparser2' {
  declare module.exports: any;
}
