// flow-typed signature: 24f4c7cb718b364c257b61761a223c35
// flow-typed version: <<STUB>>/humanize-plus_v1.8.2/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'humanize-plus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'humanize-plus' {
  declare function oxford(string[]): string;

  declare var exports: {
    oxford: oxford,
  };
}
