// flow-typed signature: c6dd605d34df83a774660533cac84122
// flow-typed version: <<STUB>>/idb-range_v3.1.3/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'idb-range'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'idb-range' {
  declare module.exports: any;
}
