// flow-typed signature: 6f9ed74042ca89bb23f81d9097736444
// flow-typed version: <<STUB>>/idb-request_v^3.2.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'idb-request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'idb-request' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'idb-request/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'idb-request/lib/index.js' {
  declare module.exports: $Exports<'idb-request/lib/index'>;
}
