// flow-typed signature: 273408af4444992212f6e40473bbabf7
// flow-typed version: <<STUB>>/idb-request_v3.2.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'idb-request'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'idb-request' {
  declare module.exports: any;
}
