// flow-typed signature: cf64ed2226ebcc8e817c35d850c7b20c
// flow-typed version: <<STUB>>/idb-range_v^3.1.3/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'idb-range'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'idb-range' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'idb-range/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'idb-range/lib/index.js' {
  declare module.exports: $Exports<'idb-range/lib/index'>;
}
