// flow-typed signature: 859f7fafe842dbd0e63076469280a5dc
// flow-typed version: <<STUB>>/is-safari_v^1.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-safari'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-safari' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'is-safari/index' {
  declare module.exports: $Exports<'is-safari'>;
}
declare module 'is-safari/index.js' {
  declare module.exports: $Exports<'is-safari'>;
}
