// flow-typed signature: 2bca9502d74d019860fb5280ddd076b3
// flow-typed version: <<STUB>>/is-safari_v1.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-safari'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-safari' {
  declare module.exports: any;
}
