// flow-typed signature: 5a6612f3e239c1def3fef83d13d12946
// flow-typed version: <<STUB>>/is-safari_v1.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-safari'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-safari' {
  declare module.exports: any;
}
