// flow-typed signature: c42a35662c60f143f5fc2e2a8ade2a71
// flow-typed version: <<STUB>>/jest-enzyme_v2.1.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-enzyme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-enzyme' {
  declare module.exports: any;
}
