// flow-typed signature: 674d62d396c19ef04d8c8bff18f2fcd3
// flow-typed version: <<STUB>>/jest-matcher-utils_v22.4.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-matcher-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-matcher-utils' {
  declare module.exports: any;
}
