// flow-typed signature: cbf181e91f477c53ee7d595291b75840
// flow-typed version: <<STUB>>/jest-styled-components_v^6.2.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-styled-components' {
  declare module.exports: any;
}
