// flow-typed signature: 1369d7d48f47a711baf9ca8ef25718e2
// flow-typed version: <<STUB>>/jest-matcher-utils_v22.1.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-matcher-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-matcher-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-matcher-utils/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-matcher-utils/build/index.js' {
  declare module.exports: $Exports<'jest-matcher-utils/build/index'>;
}
