// flow-typed signature: 2d8fe986fe92bb43d1d2ca4c67d5068e
// flow-typed version: <<STUB>>/jest-matcher-utils_v^22.4.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-matcher-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-matcher-utils' {
  declare module.exports: any;
}
