// flow-typed signature: af49c8490c78b55fe6d534a8b1c59707
// flow-typed version: <<STUB>>/js-beautify_v1.6.8/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-beautify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-beautify' {
  declare module.exports: any;
}
