// flow-typed signature: dcb549fd7111a608480ec63b5f1edb4a
// flow-typed version: <<STUB>>/js-yaml_v3.11.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-yaml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-yaml' {
  declare module.exports: any;
}
