// flow-typed signature: b643e3e24d9abb730d16a64e9ec44e88
// flow-typed version: <<STUB>>/js-yaml_v3.8.4/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-yaml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-yaml' {
  declare module.exports: any;
}
