// flow-typed signature: d19f04ee7b9e85a74122cbb694c5bc2a
// flow-typed version: <<STUB>>/js-yaml_v^3.12.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-yaml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-yaml' {
  declare module.exports: any;
}
