// flow-typed signature: d2fc059a955c37708842e350d62bb9ae
// flow-typed version: <<STUB>>/json-loader_v0.5.4/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-loader' {
  declare module.exports: any;
}
