// flow-typed signature: 705ad0de7c2899d7043b9f4e2381703c
// flow-typed version: <<STUB>>/junk_v2.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'junk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'junk' {
  declare module.exports: any;
}
