// flow-typed signature: bd345edf10e36bf0b3a8afc475b3ce0b
// flow-typed version: <<STUB>>/junk_v^2.1.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'junk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'junk' {
  declare module.exports: any;
}
