// flow-typed signature: 7945aef87fb12aace5bd466aa515c80b
// flow-typed version: <<STUB>>/keymage_v1.1.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'keymage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'keymage' {
  declare module.exports: any;
}
