// flow-typed signature: a696e5bd10301b6e82dbcca3e2032434
// flow-typed version: <<STUB>>/keymage_v^1.1.3/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'keymage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'keymage' {
  declare module.exports: any;
}
