// flow-typed signature: fc1955cd71569c19c8f12f064137482b
// flow-typed version: <<STUB>>/keymage_v^1.1.3/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'keymage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'keymage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'keymage/keymage' {
  declare module.exports: any;
}

declare module 'keymage/keymage.min' {
  declare module.exports: any;
}

declare module 'keymage/test/phantom' {
  declare module.exports: any;
}

declare module 'keymage/test/test' {
  declare module.exports: any;
}

declare module 'keymage/test/vendor/wru.console.max' {
  declare module.exports: any;
}

declare module 'keymage/test/vendor/wru.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'keymage/keymage.js' {
  declare module.exports: $Exports<'keymage/keymage'>;
}
declare module 'keymage/keymage.min.js' {
  declare module.exports: $Exports<'keymage/keymage.min'>;
}
declare module 'keymage/test/phantom.js' {
  declare module.exports: $Exports<'keymage/test/phantom'>;
}
declare module 'keymage/test/test.js' {
  declare module.exports: $Exports<'keymage/test/test'>;
}
declare module 'keymage/test/vendor/wru.console.max.js' {
  declare module.exports: $Exports<'keymage/test/vendor/wru.console.max'>;
}
declare module 'keymage/test/vendor/wru.min.js' {
  declare module.exports: $Exports<'keymage/test/vendor/wru.min'>;
}
