// flow-typed signature: a9f71b49963378a763655a57ee7654be
// flow-typed version: <<STUB>>/keyv-file_v^0.1.7/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'keyv-file'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'keyv-file' {
  declare module.exports: any;
}
