// flow-typed signature: aecb493bab94527bb5bef71f6726be6b
// flow-typed version: <<STUB>>/keyv_v^3.1.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'keyv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'keyv' {
  declare module.exports: any;
}
