// flow-typed signature: 334d6a51429b90eeaa4b46abf592b3dc
// flow-typed version: <<STUB>>/listify_v^1.0.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'listify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'listify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'listify/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'listify/index' {
  declare module.exports: $Exports<'listify'>;
}
declare module 'listify/index.js' {
  declare module.exports: $Exports<'listify'>;
}
declare module 'listify/test.js' {
  declare module.exports: $Exports<'listify/test'>;
}
