// flow-typed signature: 9bed3805cd2369af8e16fef06ff2e060
// flow-typed version: <<STUB>>/lz-string_v^1.4.4/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lz-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lz-string' {
  declare module.exports: any;
}
