// flow-typed signature: 223298fdfc0b9d058d1dbd1c240484e6
// flow-typed version: <<STUB>>/mem_v^4.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mem'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mem' {
  declare module.exports: any;
}
