// flow-typed signature: ebb86aa5abda34d1f7dff67f8c58f7f8
// flow-typed version: <<STUB>>/meow_v^5.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'meow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'meow' {
  declare module.exports: any;
}
