// flow-typed signature: c652e6fab81d6705337fdc64be5ef365
// flow-typed version: <<STUB>>/mini-css-extract-plugin_v^0.4.3/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mini-css-extract-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mini-css-extract-plugin' {
  declare module.exports: any;
}
