// flow-typed signature: a41c1cf9dc6c8824fb647d49e9b60879
// flow-typed version: <<STUB>>/mock-require_v2.0.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mock-require'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mock-require' {
  declare module.exports: any;
}
