// flow-typed signature: f03144d57204696124be61dfcaf702c6
// flow-typed version: <<STUB>>/node-fetch_v2.0.0-alpha.3/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-fetch' {
  declare module.exports: any;
}
