// flow-typed signature: a09d021c5a57e56a4707da2e032ae1d5
// flow-typed version: <<STUB>>/node-fetch_v2.0.0-alpha.7/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-fetch' {
  declare module.exports: any;
}
