// flow-typed signature: 740701be4c2e099ef8a0da0986b26873
// flow-typed version: <<STUB>>/node-sass_v4.7.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-sass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-sass' {
  declare module.exports: any;
}
