// flow-typed signature: 5a564a73e71af9f4ff0b20df0e40dd59
// flow-typed version: <<STUB>>/node-sass_v4.8.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-sass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-sass' {
  declare module.exports: any;
}
