// flow-typed signature: f79fe25002e9b914ecd668e9b8c72c2a
// flow-typed version: <<STUB>>/node-sass_v4.5.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-sass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-sass' {
  declare module.exports: any;
}
