// flow-typed signature: eb5e896c7f76086554d92cc224811c4c
// flow-typed version: <<STUB>>/nomnom_v1.8.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nomnom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nomnom' {
  declare module.exports: any;
}
