// flow-typed signature: 69271a51b6d1293b34e868ff252c8f02
// flow-typed version: <<STUB>>/nomnom_v1.8.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nomnom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nomnom' {
  declare module.exports: any;
}
