// flow-typed signature: 919e53c66a0802a09a95e3b6c5fb7aa8
// flow-typed version: <<STUB>>/nomnom_v^1.8.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nomnom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nomnom' {
  declare module.exports: any;
}
