// flow-typed signature: 60025bde4e74f11c19497dd2b22b80b4
// flow-typed version: <<STUB>>/nyc_v10.1.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nyc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nyc' {
  declare module.exports: any;
}
