// flow-typed signature: f99e73ddcd1674c35213367212233e78
// flow-typed version: <<STUB>>/ord_v0.1.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ord'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ord' {
  declare module.exports: any;
}
