// flow-typed signature: 457c74151339bc850b50baa140334227
// flow-typed version: <<STUB>>/p-props_v1.1.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-props'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-props' {
  declare module.exports: any;
}
