// flow-typed signature: 5df0b246db98d6ecd3781687ec6abcd1
// flow-typed version: <<STUB>>/p-props_v1.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-props'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-props' {
  declare module.exports: any;
}
