// flow-typed signature: 95db2fdc8691a0ae9513aa9ff1aea5e9
// flow-typed version: <<STUB>>/p-props_v^1.2.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-props'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-props' {
  declare module.exports: any;
}
