// flow-typed signature: 0813d51cdc999e0fe705f84b1140fdfe
// flow-typed version: <<STUB>>/p-queue_v1.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-queue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-queue' {
  declare module.exports: any;
}
