// flow-typed signature: 692b861d6e26e8814b669f8a46ca7182
// flow-typed version: <<STUB>>/p-series_v1.0.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-series'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-series' {
  declare module.exports: any;
}
