// flow-typed signature: f0a1289f840aec38abd9c6fc82a5929b
// flow-typed version: <<STUB>>/p-settle_v2.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-settle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-settle' {
  declare module.exports: any;
}
