// flow-typed signature: 9d175ae3fb791d85f4c5cde2a15dc44c
// flow-typed version: <<STUB>>/p-series_v1.1.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-series'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-series' {
  declare module.exports: any;
}
