// flow-typed signature: 73bcac411f4d50797d984966363e754b
// flow-typed version: <<STUB>>/p-series_v^1.1.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-series'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-series' {
  declare module.exports: any;
}
