// flow-typed signature: 23a00b62af46cf4efc2fbb300e07adf0
// flow-typed version: <<STUB>>/p-settle_v2.1.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-settle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-settle' {
  declare module.exports: any;
}
