// flow-typed signature: 59fb5a4c66ba9c8af4a05834feef8496
// flow-typed version: <<STUB>>/pegjs_v0.10.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pegjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pegjs' {
  declare module.exports: any;
}
