// flow-typed signature: 68f7ddf40484eb9aed74d98db8ecff15
// flow-typed version: <<STUB>>/pegjs_v^0.10.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pegjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pegjs' {
  declare module.exports: any;
}
