// flow-typed signature: fced9ae5a0b9cb723b7e71b07852f42a
// flow-typed version: <<STUB>>/pify_v2.3.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pify' {
  declare module.exports: any;
}
