// flow-typed signature: a0c27dbbc7129c01a91bcda39e3ecae7
// flow-typed version: <<STUB>>/pify_v2.3.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pify' {
  declare module.exports: any;
}
