// flow-typed signature: aa717e75ccb588b43e0adba687fb93c3
// flow-typed version: <<STUB>>/pify_v2.3.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pify' {
  declare module.exports: any;
}
