// flow-typed signature: 67c3a86d48024003e5052c114a79fdbc
// flow-typed version: <<STUB>>/plur_v2.1.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'plur'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'plur' {
  declare module.exports: any;
}
