// flow-typed signature: 7de552b6ee55d8db8cb6601539f95b2f
// flow-typed version: <<STUB>>/plur_v^2.1.2/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'plur'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'plur' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'plur/index' {
  declare module.exports: $Exports<'plur'>;
}
declare module 'plur/index.js' {
  declare module.exports: $Exports<'plur'>;
}
