// flow-typed signature: 7f0638eee970f10d93a2cc1382756bf9
// flow-typed version: <<STUB>>/plur_v^3.0.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'plur'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'plur' {
  declare module.exports: any;
}
