// flow-typed signature: d846453f1c258373cdb4804a5773f396
// flow-typed version: <<STUB>>/preact-compat_v3.11.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact-compat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact-compat' {
  declare module.exports: any;
}
