// flow-typed signature: 38a962c6f3c11c35cfb0f18b294c7450
// flow-typed version: <<STUB>>/present_v1.0.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'present'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'present' {
  declare module.exports: any;
}
