// flow-typed signature: 7537a3ae9713088de1f271b1f9dd355e
// flow-typed version: <<STUB>>/present_v1.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'present'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'present' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'present/gulpfile' {
  declare module.exports: any;
}

declare module 'present/lib/present-browser' {
  declare module.exports: any;
}

declare module 'present/lib/present-node' {
  declare module.exports: any;
}

declare module 'present/present' {
  declare module.exports: any;
}

declare module 'present/present.min' {
  declare module.exports: any;
}

declare module 'present/test/index' {
  declare module.exports: any;
}

declare module 'present/test/present' {
  declare module.exports: any;
}

// Filename aliases
declare module 'present/gulpfile.js' {
  declare module.exports: $Exports<'present/gulpfile'>;
}
declare module 'present/lib/present-browser.js' {
  declare module.exports: $Exports<'present/lib/present-browser'>;
}
declare module 'present/lib/present-node.js' {
  declare module.exports: $Exports<'present/lib/present-node'>;
}
declare module 'present/present.js' {
  declare module.exports: $Exports<'present/present'>;
}
declare module 'present/present.min.js' {
  declare module.exports: $Exports<'present/present.min'>;
}
declare module 'present/test/index.js' {
  declare module.exports: $Exports<'present/test/index'>;
}
declare module 'present/test/present.js' {
  declare module.exports: $Exports<'present/test/present'>;
}
