// flow-typed signature: d392b03178f31ad925514428e532ceba
// flow-typed version: <<STUB>>/present_v1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'present'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'present' {
  declare module.exports: any;
}
