// flow-typed signature: 9232eab22a9117de9a37576b67194780
// flow-typed version: <<STUB>>/pretty-quick_v1.4.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pretty-quick'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pretty-quick' {
  declare module.exports: any;
}
