// flow-typed signature: 078842eb852124e7e98497f4cae36539
// flow-typed version: <<STUB>>/pretty-ms_v2.1.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pretty-ms'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pretty-ms' {
  declare module.exports: any;
}
