// flow-typed signature: 5b16fd5de24edd7b49c40b083c12914d
// flow-typed version: <<STUB>>/prettier_v1.10.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier' {
  declare module.exports: any;
}
