// flow-typed signature: 8e750467264db8902d62c0dee06c4cf1
// flow-typed version: <<STUB>>/prettier_v1.3.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier' {
  declare module.exports: any;
}
