// flow-typed signature: 90072aadb9a8a8fdfa40623ca5fc1c0c
// flow-typed version: <<STUB>>/pretty-quick_v^1.6.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pretty-quick'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pretty-quick' {
  declare module.exports: any;
}
