// flow-typed signature: fe049a6c3c01520efc785d75431ffda1
// flow-typed version: <<STUB>>/prettier_v0.0.10/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier' {
  declare module.exports: any;
}
