// flow-typed signature: b275461ad2bacbb21405f73908bfaa77
// flow-typed version: <<STUB>>/pretty-ms_v2.1.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pretty-ms'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pretty-ms' {
  declare module.exports: any;
}
