// flow-typed signature: ea20686141cdf7f31954fb624fbdc215
// flow-typed version: <<STUB>>/react-select_v1.0.0-rc.5/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-select' {
  declare module.exports: any;
}
