// flow-typed signature: e37ad875ef77222de7da3766047b65a2
// flow-typed version: <<STUB>>/react-input-autosize_v1.1.4/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-input-autosize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-input-autosize' {
  declare module.exports: any;
}
