// flow-typed signature: 636e1a107f52de37995de969d8f0383f
// flow-typed version: <<STUB>>/react-test-renderer_v15.5.4/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-test-renderer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-test-renderer' {
  declare module.exports: any;
}
