// flow-typed signature: 060989c6ee925fd8ed2edf648b4e8f9c
// flow-typed version: <<STUB>>/react-document-title_v^2.0.3/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-document-title'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-document-title' {
  declare module.exports: any;
}
