// flow-typed signature: 9062d294f4f139ffd879b9a65da9389d
// flow-typed version: <<STUB>>/react-radio-group_v3.0.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-radio-group'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-radio-group' {
  declare module.exports: any;
}
