// flow-typed signature: bfa5a47c261f597cc67235d9d12f28fe
// flow-typed version: <<STUB>>/react-codemirror2_v4.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-codemirror2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-codemirror2' {
  declare module.exports: any;
}
