// flow-typed signature: 20bd12378cf0e549ccfa0c3bf9e0b832
// flow-typed version: <<STUB>>/react-virtualized-auto-sizer_v^1.0.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-virtualized-auto-sizer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-virtualized-auto-sizer' {
  declare module.exports: any;
}
