// flow-typed signature: eab733229e9ff342f6ca69f6331d2d53
// flow-typed version: <<STUB>>/react-codemirror2_v4.2.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-codemirror2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-codemirror2' {
  declare module.exports: any;
}
