// flow-typed signature: 90a6e3e66068b0069d7fa30a4700317a
// flow-typed version: <<STUB>>/react-router_v3.0.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router' {
  declare module.exports: any;
}
