// flow-typed signature: ebec23f8bc0c39cc757f8bdf8310423f
// flow-typed version: <<STUB>>/react-document-title_v2.0.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-document-title'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-document-title' {
  declare module.exports: any;
}
