// flow-typed signature: be9587aaa6c997210c78770ffcb39bf4
// flow-typed version: <<STUB>>/react-radio-group_v3.0.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-radio-group'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-radio-group' {
  declare module.exports: any;
}
