// flow-typed signature: b8656863603a405a1781aacd7aa90444
// flow-typed version: <<STUB>>/react-dropzone_v3.9.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dropzone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dropzone' {
  declare module.exports: any;
}
