// flow-typed signature: 26836412583df6cdda81c18c2b955cc2
// flow-typed version: <<STUB>>/react-modal_v^3.1.0/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-modal' {
  declare module.exports: any;
}
