// flow-typed signature: e2e0c9ff4c3840cc38860d101f20f80e
// flow-typed version: <<STUB>>/react-dropzone_v3.13.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dropzone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dropzone' {
  declare module.exports: any;
}
