// flow-typed signature: 539c91dae9f6ee7e4b4af00082142c35
// flow-typed version: <<STUB>>/react-radio-group_v3.0.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-radio-group'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-radio-group' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-radio-group/lib/index' {
  declare module.exports: any;
}

declare module 'react-radio-group/umd/index' {
  declare module.exports: any;
}

declare module 'react-radio-group/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-radio-group/lib/index.js' {
  declare module.exports: $Exports<'react-radio-group/lib/index'>;
}
declare module 'react-radio-group/umd/index.js' {
  declare module.exports: $Exports<'react-radio-group/umd/index'>;
}
declare module 'react-radio-group/webpack.config.js' {
  declare module.exports: $Exports<'react-radio-group/webpack.config'>;
}
