// flow-typed signature: f860c466019ecc3174a0c1797a3ca09a
// flow-typed version: <<STUB>>/react-addons-perf_v15.4.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-addons-perf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-addons-perf' {
  declare module.exports: any;
}
