// flow-typed signature: f403336f1a7efcb0ea7c22a6374a2078
// flow-typed version: <<STUB>>/react-dropzone_v3.12.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dropzone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dropzone' {
  declare module.exports: any;
}
