// flow-typed signature: c19b22de548eab1ef7c80ff1ec0e4502
// flow-typed version: <<STUB>>/react-codemirror_v1.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-codemirror'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-codemirror' {
  declare module.exports: any;
}
