// flow-typed signature: a784bd5797ea60da90b1452695c4b376
// flow-typed version: <<STUB>>/react-codemirror_v0.3.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-codemirror'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-codemirror' {
  declare module.exports: any;
}
