// flow-typed signature: fadf02bc93e79cf13d153132f4885e43
// flow-typed version: <<STUB>>/redux-promise_v0.5.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-promise' {
  declare module.exports: any;
}
