// flow-typed signature: 8ef9000c4a854ab76ac4d5d8369dd5ae
// flow-typed version: <<STUB>>/redux-devtools_v3.4.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-devtools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-devtools' {
  declare module.exports: any;
}
