// flow-typed signature: 42b2735e387e99ff830dfcd2b0c3aa09
// flow-typed version: <<STUB>>/redux-promise_v^0.5.3/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-promise' {
  declare module.exports: any;
}
