// flow-typed signature: 249ced6d8096c67df55976af394d99ce
// flow-typed version: <<STUB>>/redux-thunk_v2.2.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-thunk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-thunk' {
  declare module.exports: any;
}
