// flow-typed signature: d208dcc1c906107e5b7f21f70b0783f8
// flow-typed version: <<STUB>>/redux-logger_v2.7.4/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-logger' {
  declare module.exports: any;
}
