// flow-typed signature: 5e9353b7baad110c49a90b16230e9fd4
// flow-typed version: <<STUB>>/redux-undo_v0.6.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-undo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-undo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-undo/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-undo/lib/index.js' {
  declare module.exports: $Exports<'redux-undo/lib/index'>;
}
