// flow-typed signature: d3e71ac42cee1f4cc93a7395aaf7e164
// flow-typed version: <<STUB>>/redux-freeze_v0.1.5/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-freeze'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-freeze' {
  declare module.exports: any;
}
