// flow-typed signature: 09a3294d4d8ef35cee7a03b327caf03d
// flow-typed version: <<STUB>>/redux-logger_v^3.0.6/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-logger' {
  declare module.exports: any;
}
