// flow-typed signature: 99f7c8a3d0a8a845a9c4fb01e5eee989
// flow-typed version: <<STUB>>/redux-undo_v0.6.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-undo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-undo' {
  declare module.exports: any;
}
