// flow-typed signature: 867a600e6b26ddfb663b6b5bb8d80bcf
// flow-typed version: <<STUB>>/redux-thunk_v2.2.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-thunk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-thunk' {
  declare module.exports: any;
}
