// flow-typed signature: 4f051cfbf74e06b919be8a21215f537f
// flow-typed version: <<STUB>>/redux-promise_v0.5.3/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-promise' {
  declare module.exports: any;
}
