// flow-typed signature: 5bed5aafb6c51985e6fb71fbf7a7b46f
// flow-typed version: <<STUB>>/redux-thunk_v^2.3.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-thunk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-thunk' {
  declare module.exports: any;
}
