// flow-typed signature: 7dc98821a3b5b616b4c08dcfcd129373
// flow-typed version: <<STUB>>/redux-devtools_v3.3.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-devtools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-devtools' {
  declare module.exports: any;
}
