// flow-typed signature: 4ce78035d4e39f8a79e94c3f9f845525
// flow-typed version: <<STUB>>/rimraf_v2.5.4/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rimraf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rimraf' {
  declare module.exports: any;
}
