// flow-typed signature: c6045cb5bf7558ec16e07a2ef280b244
// flow-typed version: <<STUB>>/rimraf_v2.6.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rimraf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rimraf' {
  declare module.exports: any;
}
