// flow-typed signature: 788faa114fcd085cdb66259a51d98c32
// flow-typed version: <<STUB>>/rimraf_v2.6.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rimraf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rimraf' {
  declare module.exports: any;
}
