// flow-typed signature: 279b144803b9b303e498768931a15fc7
// flow-typed version: <<STUB>>/sass_v^1.94.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass' {
  declare module.exports: any;
}
