// flow-typed signature: 820040ec29d97917abd8283e5df843e4
// flow-typed version: <<STUB>>/sass-loader_v7.0.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass-loader' {
  declare module.exports: any;
}
