// flow-typed signature: d9b197b034b4cfb2b8b9c0e7f7e480f3
// flow-typed version: <<STUB>>/sass-loader_v6.0.6/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass-loader' {
  declare module.exports: any;
}
