// flow-typed signature: 486959de46f5669fdbcbdf98cccbc5df
// flow-typed version: <<STUB>>/sass-loader_v6.0.3/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sass-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sass-loader' {
  declare module.exports: any;
}
