// flow-typed signature: 4b37c0bc3bfc622a87abc97974161ff9
// flow-typed version: <<STUB>>/serialize-error_v2.1.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serialize-error'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serialize-error' {
  declare module.exports: any;
}
