// flow-typed signature: 77a0770d432dbcb648846dd79aee5bb2
// flow-typed version: <<STUB>>/serialize-error_v^2.1.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serialize-error'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serialize-error' {
  declare module.exports: any;
}
