// flow-typed signature: 87f166d2e2ab511ca3d3e92f6661feae
// flow-typed version: <<STUB>>/sparkly_v^4.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sparkly'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sparkly' {
  declare module.exports: any;
}
