// flow-typed signature: 009792813464e87ca112b2f12301306b
// flow-typed version: <<STUB>>/sparkly_v^3.1.2/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sparkly'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sparkly' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'sparkly/index' {
  declare module.exports: $Exports<'sparkly'>;
}
declare module 'sparkly/index.js' {
  declare module.exports: $Exports<'sparkly'>;
}
