// flow-typed signature: c04c684eb7da12858e137c8545e319d3
// flow-typed version: <<STUB>>/sparkly_v3.1.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sparkly'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sparkly' {
  declare module.exports: any;
}
