// flow-typed signature: ea94bbf6b3532c72bddac5627cc434a5
// flow-typed version: <<STUB>>/stabilize_v1.0.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stabilize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stabilize' {
  declare function exports(
    value: any,
    replacer?: (Array<any> | (key: any, value: any) => any),
    space?: string | number,
  ): string;
}
