// flow-typed signature: ee8f2f8796c3a496b65bd2043310434d
// flow-typed version: <<STUB>>/stabilize_v1.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stabilize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stabilize' {
  declare module.exports: any;
}
