// flow-typed signature: 88bb51b559055f8438f4cdc3ca4e6f27
// flow-typed version: <<STUB>>/stabilize_v1.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stabilize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stabilize' {
  declare export default function stringify(
    value: any,
    replacer?: (Array<any> | (key: any, value: any) => any),
    space?: string | number,
  ): string;
}
