// flow-typed signature: 392c7f783e90c353e0338a37faf6de74
// flow-typed version: <<STUB>>/stabilize_v^1.0.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stabilize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stabilize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stabilize/example/key_cmp' {
  declare module.exports: any;
}

declare module 'stabilize/example/nested' {
  declare module.exports: any;
}

declare module 'stabilize/example/str' {
  declare module.exports: any;
}

declare module 'stabilize/example/value_cmp' {
  declare module.exports: any;
}

declare module 'stabilize/test/cmp' {
  declare module.exports: any;
}

declare module 'stabilize/test/nested' {
  declare module.exports: any;
}

declare module 'stabilize/test/replacer' {
  declare module.exports: any;
}

declare module 'stabilize/test/space' {
  declare module.exports: any;
}

declare module 'stabilize/test/str' {
  declare module.exports: any;
}

declare module 'stabilize/test/to-json' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stabilize/example/key_cmp.js' {
  declare module.exports: $Exports<'stabilize/example/key_cmp'>;
}
declare module 'stabilize/example/nested.js' {
  declare module.exports: $Exports<'stabilize/example/nested'>;
}
declare module 'stabilize/example/str.js' {
  declare module.exports: $Exports<'stabilize/example/str'>;
}
declare module 'stabilize/example/value_cmp.js' {
  declare module.exports: $Exports<'stabilize/example/value_cmp'>;
}
declare module 'stabilize/index' {
  declare module.exports: $Exports<'stabilize'>;
}
declare module 'stabilize/index.js' {
  declare module.exports: $Exports<'stabilize'>;
}
declare module 'stabilize/test/cmp.js' {
  declare module.exports: $Exports<'stabilize/test/cmp'>;
}
declare module 'stabilize/test/nested.js' {
  declare module.exports: $Exports<'stabilize/test/nested'>;
}
declare module 'stabilize/test/replacer.js' {
  declare module.exports: $Exports<'stabilize/test/replacer'>;
}
declare module 'stabilize/test/space.js' {
  declare module.exports: $Exports<'stabilize/test/space'>;
}
declare module 'stabilize/test/str.js' {
  declare module.exports: $Exports<'stabilize/test/str'>;
}
declare module 'stabilize/test/to-json.js' {
  declare module.exports: $Exports<'stabilize/test/to-json'>;
}
