// flow-typed signature: 22c3737285eb1da8cc1d3d5c9ec14c37
// flow-typed version: <<STUB>>/sto-sis-time-parser_v2.2.11/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sto-sis-time-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sto-sis-time-parser' {
  declare module.exports: any;
}
