// flow-typed signature: 98d88d86be55610845ac249e5e7da3ed
// flow-typed version: <<STUB>>/sto-sis-time-parser_v^2.2.11/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sto-sis-time-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sto-sis-time-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sto-sis-time-parser/lib/check-courses-for-time-conflicts' {
  declare module.exports: any;
}

declare module 'sto-sis-time-parser/lib/check-schedule-for-time-conflicts' {
  declare module.exports: any;
}

declare module 'sto-sis-time-parser/lib/convert-time-strings-to-offerings' {
  declare module.exports: any;
}

declare module 'sto-sis-time-parser/lib/find-days' {
  declare module.exports: any;
}

declare module 'sto-sis-time-parser/lib/find-schedule-time-conflicts' {
  declare module.exports: any;
}

declare module 'sto-sis-time-parser/lib/find-time' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sto-sis-time-parser/index' {
  declare module.exports: $Exports<'sto-sis-time-parser'>;
}
declare module 'sto-sis-time-parser/index.js' {
  declare module.exports: $Exports<'sto-sis-time-parser'>;
}
declare module 'sto-sis-time-parser/lib/check-courses-for-time-conflicts.js' {
  declare module.exports: $Exports<'sto-sis-time-parser/lib/check-courses-for-time-conflicts'>;
}
declare module 'sto-sis-time-parser/lib/check-schedule-for-time-conflicts.js' {
  declare module.exports: $Exports<'sto-sis-time-parser/lib/check-schedule-for-time-conflicts'>;
}
declare module 'sto-sis-time-parser/lib/convert-time-strings-to-offerings.js' {
  declare module.exports: $Exports<'sto-sis-time-parser/lib/convert-time-strings-to-offerings'>;
}
declare module 'sto-sis-time-parser/lib/find-days.js' {
  declare module.exports: $Exports<'sto-sis-time-parser/lib/find-days'>;
}
declare module 'sto-sis-time-parser/lib/find-schedule-time-conflicts.js' {
  declare module.exports: $Exports<'sto-sis-time-parser/lib/find-schedule-time-conflicts'>;
}
declare module 'sto-sis-time-parser/lib/find-time.js' {
  declare module.exports: $Exports<'sto-sis-time-parser/lib/find-time'>;
}
