// flow-typed signature: 6a00765c28651ee910bc1765b57c41d4
// flow-typed version: <<STUB>>/sto-course-related-data_v^4.0.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sto-course-related-data'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sto-course-related-data' {
  declare module.exports: any;
}
