// flow-typed signature: 87e1169a5a90d5bc93af3ee0b6f3074f
// flow-typed version: <<STUB>>/sto-course-related-data_v4.0.2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sto-course-related-data'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sto-course-related-data' {
  declare module.exports: any;
}
