// flow-typed signature: 89e2b027afa10c77971ea950fafde074
// flow-typed version: <<STUB>>/style-loader_v0.18.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'style-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'style-loader' {
  declare module.exports: any;
}
