// flow-typed signature: d8b78195c5d8be700fa0155fbf301481
// flow-typed version: <<STUB>>/styled-components_v^4.0.0-beta.8/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-components' {
  declare module.exports: any;
}
