// flow-typed signature: 20b978fc2b502355478c8b29bb6cdc27
// flow-typed version: <<STUB>>/style-loader_v0.20.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'style-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'style-loader' {
  declare module.exports: any;
}
