// flow-typed signature: 75167a84ad2861e495dd0fd37f74c204
// flow-typed version: <<STUB>>/style-loader_v0.13.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'style-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'style-loader' {
  declare module.exports: any;
}
