// flow-typed signature: 39ac6adab96fe4274336d756fcaae3e0
// flow-typed version: <<STUB>>/styled-components_v1.4.4/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'styled-components' {
  declare module.exports: any;
}
