// flow-typed signature: fe63827f56d6a32d9ad77b7c2f4d318d
// flow-typed version: <<STUB>>/text-table_v0.2.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'text-table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'text-table' {
  declare module.exports: any;
}
