// flow-typed signature: 2a9ae845f113082f5e518d3c42e39263
// flow-typed version: <<STUB>>/text-table_v0.2.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'text-table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'text-table' {
  declare module.exports: any;
}
