// flow-typed signature: ad09446e11d7b0178aa19eff43d6bc15
// flow-typed version: <<STUB>>/treo_v0.6.0-rc2/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'treo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'treo' {
  declare module.exports: any;
}
