// flow-typed signature: d4084b0ceff17bceaf4a07f83c4e9437
// flow-typed version: <<STUB>>/typeface-fira-sans_v^0.0.54/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-fira-sans'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-fira-sans' {
  declare module.exports: any;
}
