// flow-typed signature: 09c36098c163baf96165b80d35f80112
// flow-typed version: <<STUB>>/uglifyjs-webpack-plugin_v1.2.4/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uglifyjs-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uglifyjs-webpack-plugin' {
  declare module.exports: any;
}
