// flow-typed signature: eb4033bde9237e0906772d57ea86f9ad
// flow-typed version: <<STUB>>/url-loader_v1.0.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url-loader' {
  declare module.exports: any;
}
