// flow-typed signature: cf34009394aba1de4f3ae6eab9aad97e
// flow-typed version: <<STUB>>/url-loader_v0.5.8/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url-loader' {
  declare module.exports: any;
}
