// flow-typed signature: 938971c38ece51f06dbfa49324fed4ae
// flow-typed version: <<STUB>>/webpack_v2.6.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack' {
  declare module.exports: any;
}
