// flow-typed signature: ccb349d73e81241565fb99539ddf67cf
// flow-typed version: <<STUB>>/webpack_v^4.19.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack' {
  declare module.exports: any;
}
