// flow-typed signature: 991688d53feb1058c16c16b2bdede181
// flow-typed version: <<STUB>>/webpack-stylish_v^0.1.8/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-stylish'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-stylish' {
  declare module.exports: any;
}
