// flow-typed signature: 5eb55c02ff4e2ce1c6df1b4feb7e02bb
// flow-typed version: <<STUB>>/webpack-cli_v^3.1.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-cli' {
  declare module.exports: any;
}
