// flow-typed signature: 574242cd17c0752ebbc9fab27fa56a2f
// flow-typed version: <<STUB>>/webpack-dev-server_v2.11.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-dev-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-dev-server' {
  declare module.exports: any;
}
