// flow-typed signature: 0c066537afccea2729952c31bb26a6f8
// flow-typed version: <<STUB>>/webpack-dev-server_v2.4.2/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-dev-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-dev-server' {
  declare module.exports: any;
}
