// flow-typed signature: f4a95db114b0dc69c0464bcea1b7a25d
// flow-typed version: <<STUB>>/webpack-dev-server_v2.2.0-rc.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-dev-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-dev-server' {
  declare module.exports: any;
}
