// flow-typed signature: 4a61bba0e794ed813eab36eafd33eadb
// flow-typed version: <<STUB>>/webpack_v3.10.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack' {
  declare module.exports: any;
}
