// flow-typed signature: 034d14f892af6cc8ece15035c33c276f
// flow-typed version: <<STUB>>/worker-loader_v0.8.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'worker-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'worker-loader' {
  declare module.exports: any;
}
