// flow-typed signature: ebfb39f3b8f603f90a5300ddf93a8ad1
// flow-typed version: <<STUB>>/worker-loader_v0.7.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'worker-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'worker-loader' {
  declare module.exports: any;
}
