// flow-typed signature: ba2de14c6ba75abcae63730c411aeaac
// flow-typed version: <<STUB>>/worker-loader_v^2.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'worker-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'worker-loader' {
  declare module.exports: any;
}
