// flow-typed signature: d8755af359ae4bb91bfd2d4d02f488d7
// flow-typed version: <<STUB>>/@babel/runtime_v^7.0.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/runtime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/runtime' {
  declare module.exports: any;
}
