'use strict';

module.exports = {
	SCHEDULE_CREATE: 'SCHEDULE_CREATE',
	SCHEDULE_DESTROY: 'SCHEDULE_DESTROY',
	SCHEDULE_DESTROY_MULTIPLE: 'SCHEDULE_DESTROY_MULTIPLE',
	SCHEDULE_RENAME: 'SCHEDULE_RENAME',
	SCHEDULE_MOVE: 'SCHEDULE_MOVE',
	SCHEDULE_REORDER: 'SCHEDULE_REORDER',
	SCHEDULE_TOGGLE_ACTIVATE: 'SCHEDULE_TOGGLE_ACTIVATE',
	SCHEDULE_COURSE_ADD: 'SCHEDULE_COURSE_ADD',
	SCHEDULE_COURSE_REMOVE: 'SCHEDULE_COURSE_REMOVE',
	SCHEDULE_COURSE_MOVE: 'SCHEDULE_COURSE_MOVE',
	SCHEDULE_UNDO: 'SCHEDULE_UNDO',
	SCHEDULE_CHANGED: 'SCHEDULE_CHANGED',
	SCHEDULE_SHOW_DETAIL: 'SCHEDULE_SHOW_DETAIL',
}
