export {evaluate} from './evaluate'
export {countCredits} from './count-credits'
export {default as pathToOverride} from './path-to-override'
export {default as pluralizeArea} from './pluralize-area'
export {default as humanizeOperator} from './humanize-operator'
export {default as simplifyCourse} from './simplify-course'
export {default as isRequirementName} from './is-requirement-name'
