export { evaluate } from "./source/evaluate.ts"
export { countCredits } from "./source/count-credits.ts"
export { default as pathToOverride } from "./source/path-to-override.ts"
export { default as pluralizeArea } from "./source/pluralize-area.ts"
export { default as humanizeOperator } from "./source/humanize-operator.ts"
export { default as simplifyCourse } from "./source/simplify-course.ts"
export { default as isRequirementName } from "@gob/hanson-format/is-requirement-name.ts"
export type * from "./source/types.ts"
