// flow-typed signature: 8ab797136031f41fb1ada9825fa2815f
// flow-typed version: <<STUB>>/@reach/component-component_v^0.1.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@reach/component-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@reach/component-component' {
  declare module.exports: any;
}
