// flow-typed signature: 4df6b91156f52cb64b0374c2cf80867f
// flow-typed version: <<STUB>>/@reach/dialog_v^0.1.2/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@reach/dialog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@reach/dialog' {
  declare module.exports: any;
}
