'use strict';

module.exports = {
	STUDENT_ENCODE: 'STUDENT_ENCODE',
	STUDENT_DECODE: 'STUDENT_DECODE',
	STUDENT_UPDATE: 'STUDENT_UPDATE',
	STUDENT_CREATE: 'STUDENT_CREATE',
	STUDENT_DESTROY: 'STUDENT_DESTROY',
	STUDENT_UNDO: 'STUDENT_UNDO',
	STUDENT_TOGGLE_ACTIVE: 'STUDENT_TOGGLE_ACTIVE',
	STUDENT_SAVE: 'STUDENT_SAVE',
	STUDENT_CHANGED: 'STUDENT_CHANGED',
}
