name: CI
permissions:
  contents: read
  security-events: write # for uploading SARIF results

on:
  push:
    branches: [trunk]
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  flow:
    name: Flow Type Checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2

      - name: Install dependencies
        run: npm ci

      - name: Run Flow
        run: mise run flow check --quiet

  test:
    name: Jest Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: mise run test -- --runInBand --coverage

      # - name: Upload coverage to Coveralls
      #   uses: coverallsapp/github-action@v2

  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: mise run lint

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: mise run lint -- --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@df559355d593797519d70b90fc8edd5db049e7a2 # v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

  format:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: |
          mise run pretty
          git diff --exit-code

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        working-directory: modules/gob-web
        run: mise run build

      - name: Rearrange files
        run: node scripts/rearrange-for-circle.js

      - name: Upload build artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: web-build
          path: ./modules/gob-web/build
